baseURL = "https://blognotes.github.io/"
languageCode = "en-us"
title = "Bruno Scopelliti"

paginate = 5

[Params]
  twitter = "@brunoscopelliti"
  twitterImage = "TODO"

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineAnchors = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "dracula"
    pygmentsUseClasses = true
    tabWidth = 2
  [markup.goldmark.renderer]
    unsafe= true

[taxonomies]
  category = "categories"
