baseURL = "https://brunoscopelliti.com/"
languageCode = "en-us"
title = "Bruno Scopelliti"

paginate = 5

[Params]
  twitter = "@brunoscopelliti"
  twitterImage = "/images/twitter-card.png"

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark.renderer]
    unsafe= true
  [markup.goldmark.extensions]
    [markup.goldmark.parser]
      autoHeadingID = true
      autoHeadingIDType = "github"
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineAnchors = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "dracula"
    pygmentsUseClasses = true
    tabWidth = 2

[taxonomies]
  category = "categories"
